# Generated by Django 3.2.5 on 2022-01-23 13:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 23, 13, 42, 4, 349016, tzinfo=utc)),
        ),
    ]
