# Generated by Django 3.2.5 on 2022-01-23 13:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_clients_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='date_ajoutee',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 23, 13, 47, 1, 463522, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='clients',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 23, 13, 47, 1, 462885, tzinfo=utc)),
        ),
    ]
