# Generated by Django 3.2.5 on 2022-01-24 11:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220123_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 24, 11, 43, 34, 388250, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='commande',
            name='date_ajoutee',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 24, 11, 43, 34, 388813, tzinfo=utc)),
        ),
    ]
